<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>7c5e72d1-f39d-4d9f-bb52-8fbdde170f2f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Maliev.Web.Client\Maliev.Web.Client.csproj" />
    <ProjectReference Include="..\Maliev.Web.Shared\Maliev.Web.Shared.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(GITHUB_ACTIONS)' != 'true'">
    <ProjectReference Include="..\..\Maliev.Aspire\Maliev.Aspire.ServiceDefaults\Maliev.Aspire.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <PackageReference Include="Maliev.Aspire.ServiceDefaults" Version="$(SharedLibraryVersion)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.7" />
    <PackageReference Include="MudBlazor" Version="9.1.0" />
  </ItemGroup>
</Project>
