<Project>
  <PropertyGroup>
    <SharedLibraryVersion Condition="'$(SharedLibraryVersion)' == ''">1.0.*-alpha*</SharedLibraryVersion>
    <MessagingContractsVersion Condition="'$(MessagingContractsVersion)' == ''">$(SharedLibraryVersion)</MessagingContractsVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.AspNetCore.SignalR.Client" Version="10.0.7" />
    <PackageReference Update="Microsoft.Extensions.Http" Version="10.0.7" />
    <PackageReference Update="Microsoft.Extensions.Localization" Version="10.0.7" />
    <PackageReference Update="Microsoft.Extensions.Localization.Abstractions" Version="10.0.7" />
    <PackageReference Update="MudBlazor" Version="9.1.0" />
    <PackageReference Update="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.7" />
    <PackageReference Update="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Update="xunit" Version="2.9.3" />
    <PackageReference Update="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageReference Update="coverlet.collector" Version="6.0.4" />
  </ItemGroup>
</Project>
